topics:
  joint_encoder: /mcu/state/jointState
  imu: /mcu/state/imu
  state_estimate: /state_estimate
  control_torques: /rml/mpc/torques

mpc_controller:
  update_rate: 100

ekf_estimator:
  update_rate: 250
  
contact_detection:
  update_rate: 250

clark_trot_controller:
  update_rate: 100
  step_duration: 0.4
  


