topics:
  joint_encoder: /mcu/state/jointState
  imu: /mcu/state/imu
  state_estimate: /state_estimate
  control_torques: /rml/mpc/torques
  terrain_map: /terrain_map
  body_plan: /body_plan
  discrete_body_plan: /discrete_body_plan
  footstep_plan: /footstep_plan
  image: /image_publisher/image

mpc_controller:
  update_rate: 100

ekf_estimator:
  update_rate: 250

global_body_planner:
  update_rate: 5

local_footstep_planner:
  update_rate: 10
  
contact_detection:
  update_rate: 250

clark_trot_controller:
  update_rate: 100
  step_duration: 0.4
  
terrain_map_publisher:
  update_rate: 10
  map_data_source: image
  resolution: 0.2
  min_height: 0.0
  max_height: 4.0

grid_map_visualization:
  grid_map_topic: /terrain_map
  grid_map_visualizations:
    - name: elevation_points
      type: point_cloud
      params:
       layer: elevation
    - name: elevation_grid
      type: occupancy_grid
      params:
       layer: elevation
       data_min: 0.08
       data_max: -0.16
